SlotsCardsConfig = {
    Album1 = {
        {
            ThemeName = "RisingOfEgypt", --显示在UI上面的主题名字，随便改
            ThemeKey = "RisingOfEgypt", --记录在数据库中的key值，发布后不能改变
            ThemeCards = {
                {CardName = "Ceramic Pot",      nID = 1,  star = 1}, --prop指该卡牌获取概率
                {CardName = "Right Eye of Horus",   nID = 2,  star = 1},
                {CardName = "The Ankh",  nID = 3,  star = 1},
                {CardName = "Emerald",    nID = 4,  star = 1},
                {CardName = "Left Eye of Horus",  nID = 5,  star = 1},
                {CardName = "Cobra",    nID = 6,  star = 1},
                {CardName = "The Scarab",     nID = 7,  star = 1},
                {CardName = "Divine Bast",     nID = 8,  star = 2},
                {CardName = "The Anubis",   nID = 9,  star = 2},
                {CardName = "The Pharaoh",   nID = 10, star = 2},
                {CardName = "The Pharaonic Woman",   nID = 11, star = 2},
                {CardName = "Rising Of Egypt",   nID = 12, star = 1}
            }
        },
        {
            ThemeName = "ChilliMexico",
            ThemeKey = "ChilliMexico",
            ThemeCards = {
                {CardName = "Maracas",    nID = 1,  star = 1},
                {CardName = "Guitar",      nID = 2,  star = 1},
                {CardName = "Chili Patse", nID = 3,  star = 1},
                {CardName = "Potato Chips",      nID = 4,  star = 1},
                {CardName = "Hat",       nID = 5,  star = 1},
                {CardName = "Tequila",       nID = 6,  star = 1},
                {CardName = "Chicken Roll",        nID = 7,  star = 1},
                {CardName = "Turkey",  nID = 8,  star = 2},
                {CardName = "Bird Pinata",     nID = 9,  star = 2},
                {CardName = "Donkey Pinata",    nID = 10, star = 2},
                {CardName = "Bull Pinata",    nID = 11, star = 2},
                {CardName = "Guitarist",    nID = 12, star = 2}
            }
        },
        {
            ThemeName = "CharmeOfChina",
            ThemeKey = "CharmeOfChina",
            ThemeCards = {
                {CardName = "Red Envelopes",       nID = 1,  star = 1},
                {CardName = "Lotus",           nID = 2,  star = 1},
                {CardName = "Chinese Knot",   nID = 3,  star = 1},
                {CardName = "Tea Set",           nID = 4,  star = 1},
                {CardName = "Lifted Sedan Chair",          nID = 5,  star = 1},
                {CardName = "Imperial Jade Seal",  nID = 6,  star = 1},
                {CardName = "The Moon",    nID = 7,  star = 2},
                {CardName = "Tai Chi",           nID = 8,  star = 2},
                {CardName = "Copper",   nID = 9,  star = 2},
                {CardName = "Cornucopia",   nID = 10, star = 2},
                {CardName = "Toad",   nID = 11, star = 3},
                {CardName = "Fortunes God",   nID = 12, star = 2},
            }
        },
        {
            ThemeName = "Yummy",
            ThemeKey = "Yummy",
            ThemeCards = {
                {CardName = "Cherry Cake",       nID = 1,  star = 1},
                {CardName = "Cherry Chocolate Cake",       nID = 2,  star = 1},
                {CardName = "Rabbit Cake",      nID = 3,  star = 1},
                {CardName = "Strawberry Cake",     nID = 4,  star = 1},
                {CardName = "Lemon Cake",   nID = 5,  star = 1},
                {CardName = "Lemon Kiwi Cake",       nID = 6,  star = 2},
                {CardName = "Blueberry Cake",           nID = 7,  star = 2},
                {CardName = "Jam Cake",       nID = 8,  star = 2},
                {CardName = "Three Layer Cake",        nID = 9,  star = 2},
                {CardName = "Four Layer Cake",  nID = 10, star = 3},
                {CardName = "Layer Cake",  nID = 11, star = 3},
                {CardName = "Cream Cake",  nID = 12, star = 2},
            }
        },
        {
            ThemeName = "WeaponsForBattle",
            ThemeKey = "WeaponsForBattle",
            ThemeCards = {
                {CardName = "Nunchaku",           nID = 1,  star = 1},
                {CardName = "Darts",               nID = 2,  star = 1},
                {CardName = "Battleax",      nID = 3,  star = 1},
                {CardName = "Shield",             nID = 4,  star = 1},
                {CardName = "Bow And Arrow",           nID = 5,  star = 1},
                {CardName = "Sword",     nID = 6,  star = 2},
                {CardName = "Knife",  nID = 7,  star = 2},
                {CardName = "Machete",          nID = 8,  star = 2},
                {CardName = "Hooker",          nID = 9,  star = 2},
                {CardName = "Sword",          nID = 10, star = 3},
                {CardName = "Armour",          nID = 11, star = 3},
                {CardName = "Crossbow",          nID = 12, star = 3},
            }
        },
        {
            ThemeName = "LuckyOfTheFortunes",
            ThemeKey = "LuckyOfTheFortunes",
            ThemeCards = {
                {CardName = "Purse",        nID = 1, star = 1},
                {CardName = "Money Jar",         nID = 2, star = 1},
                {CardName = "Blue Chest",    nID = 3, star = 1},
                {CardName = "Cornucopia",       nID = 4, star = 1},
                {CardName = "Big Purse",        nID = 5, star = 2},
                {CardName = "Red Chest",    nID = 6, star = 2},
                {CardName = "Wooden Chest",          nID = 7, star = 2},
                {CardName = "Gold Purse",          nID = 8, star = 3},
                {CardName = "Gold Coins Bowl",        nID = 9, star = 3},
                {CardName = "Green Chest",     nID = 10, star = 3},
                {CardName = "Gold Chest",     nID = 11, star = 4},
                {CardName = "Gold Tree",     nID = 12, star = 4},
            }
        },
        {
            ThemeName = "ExploringTreasure",
            ThemeKey = "ExploringTreasure",
            ThemeCards = {
                {CardName = "Torch",                   nID = 1,  star = 1},
                {CardName = "Whip",             nID = 2,  star = 1},
                {CardName = "Revolver",                 nID = 3,  star = 1},
                {CardName = "Book",             nID = 4,  star = 2},
                {CardName = "Cowboy hat",                nID = 5,  star = 2},
                {CardName = "Telescope",   nID = 6,  star = 2},
                {CardName = "Binoculars",         nID = 7,  star = 2},
                {CardName = "Reel Barrel",                nID = 8,  star = 3},
                {CardName = "Pocket Watch",               nID = 9,  star = 3},
                {CardName = "Leather Handbag",           nID = 10, star = 4},
                {CardName = "Engonus",           nID = 11, star = 4},
                {CardName = "Pyramidt",           nID = 12, star = 4},
            }
        },
        {
            ThemeName = "LuxuriousLife",
            ThemeKey = "LuxuriousLife",
            ThemeCards = {
                {CardName = "Water Cup",        nID = 1,  star = 1},
                {CardName = "Sunglasses",         nID = 2,  star = 1},
                {CardName = "Perfume",             nID = 3,  star = 1},
                {CardName = "Belt",               nID = 4,  star = 2},
                {CardName = "Luxury bag",     nID = 5,  star = 2},
                {CardName = "Cosmetics",           nID = 6,  star = 2},
                {CardName = "Watch",       nID = 7,  star = 3},
                {CardName = "Camera",                nID = 8,  star = 3},
                {CardName = "Motorcycle",             nID = 9,  star = 4},
                {CardName = "Bentley",            nID = 10, star = 4},
                {CardName = "Helicopter",            nID = 11, star = 4},
                {CardName = "Speedboat",            nID = 12, star = 4},
            }
        },
        {
            ThemeName = "LuckyVegas",
            ThemeKey = "LuckyVegas",
            ThemeCards = {
                {CardName = "Blue Bar",      nID = 1,  star = 1},
                {CardName = "Violet Bar",              nID = 2,  star = 1},
                {CardName = "Gold Bar",   nID = 3,  star = 2},
                {CardName = "Bell",         nID = 4,  star = 2},
                {CardName = "Cherry",     nID = 5,  star = 2},
                {CardName = "Money",        nID = 6,  star = 3},
                {CardName = "Goblet",      nID = 7,  star = 3},
                {CardName = "Gold Dice",      nID = 8,  star = 3},
                {CardName = "Diamond Ring",         nID = 9,  star = 4},
                {CardName = "Gold Watch",        nID = 10, star = 4},
                {CardName = "City Girl",        nID = 11, star = 5},
                {CardName = "Red Diamond",        nID = 12, star = 4},
            }
        },
        {
            ThemeName = "SweetLove",
            ThemeKey = "SweetLove",
            ThemeCards = {
                {CardName = "Love Balloon",         nID = 1,  star = 1},
                {CardName = "Sunflower",       nID = 2,  star = 1},
                {CardName = "Red Wine",  nID = 3,  star = 2},
                {CardName = "Picnic",         nID = 4,  star = 2},
                {CardName = "Cake", nID = 5,  star = 2},
                {CardName = "Chocolates",       nID = 6,  star = 3},
                {CardName = "Perfume",      nID = 7,  star = 3},
                {CardName = "Necklace",       nID = 8,  star = 3},
                {CardName = "Gift",       nID = 9,  star = 4},
                {CardName = "High-heeled Shoes",    nID = 10, star = 4},
                {CardName = "Bag",    nID = 11, star = 5},
                {CardName = "Rose",    nID = 12, star = 5},
            }
        },
        {
            ThemeName = "WestWorld",
            ThemeKey = "WestWorld",
            ThemeCards = {
                {CardName = "Whip",      nID = 1,  star = 1},
                {CardName = "Sheriff",         nID = 2,  star = 1},
                {CardName = "Bullet Clip",        nID = 3,  star = 2},
                {CardName = "Boots",      nID = 4,  star = 2},
                {CardName = "Cowboy Hat",     nID = 5,  star = 2},
                {CardName = "Revolver",          nID = 6,  star = 3},
                {CardName = "Pocket",      nID = 7,  star = 3},
                {CardName = "Purse",         nID = 8,  star = 4},
                {CardName = "Saddle",      nID = 9,  star = 4},
                {CardName = "Bounty",             nID = 10, star = 4},
                {CardName = "Reward",             nID = 11, star = 5},
                {CardName = "White Horse",             nID = 12, star = 5},
            }
        },
        {
            ThemeName = "HotPot",
            ThemeKey = "HotPot",
            ThemeCards = {
                {CardName = "Beef",      nID = 1,  star = 1},
                {CardName = "Romaine Lettuce",    nID = 2,  star = 1},
                {CardName = "Beef omasum",      nID = 3,  star = 2},
                {CardName = "Mutton Rolls",          nID = 4,  star = 2},
                {CardName = "Sausage",   nID = 5,  star = 3},
                {CardName = "Mushrooms",        nID = 6,  star = 3},
                {CardName = "Beancurd Cube",         nID = 7,  star = 4},
                {CardName = "Flammulina Velutipes",           nID = 8,  star = 4},
                {CardName = "Corn",          nID = 9,  star = 4},
                {CardName = "Shrimp",     nID = 10, star = 5},
                {CardName = "Tripe",     nID = 11, star = 5},
                {CardName = "Pepper",     nID = 12, star = 5},
            }
        },
        {
            ThemeName = "GoldenRush",
            ThemeKey = "GoldenRush",
            ThemeCards = {
                {CardName = "Whiskey",      nID = 1,  star = 2},
                {CardName = "Shovel",      nID = 2,  star = 2},
                {CardName = "Pick",    nID = 3,  star = 2},
                {CardName = "Oil Lamp",     nID = 4,  star = 3},
                {CardName = "Goggles",       nID = 5,  star = 3},
                {CardName = "Helmet",  nID = 6,  star = 3},
                {CardName = "Tool",    nID = 7,  star = 4},
                {CardName = "Bomb",      nID = 8,  star = 4},
                {CardName = "Gold",      nID = 9,  star = 4},
                {CardName = "Bullion",      nID = 10, star = 5},
                {CardName = "Miner",      nID = 11, star = 5},
                {CardName = "Diamonds",      nID = 12, star = 5},
            }
        },
        {
            ThemeName = "FruitForFun",
            ThemeKey = "FruitForFun",
            ThemeCards = {
                {CardName = "Raspberry",     nID = 1,  star = 2},
                {CardName = "Apple",     nID = 2,  star = 2},
                {CardName = "Peach",      nID = 3,  star = 3},
                {CardName = "Blueberry",    nID = 4,  star = 3},
                {CardName = "Carrot",    nID = 5,  star = 3},
                {CardName = "Strawberry",      nID = 6,  star = 4},
                {CardName = "Orange", nID = 7,  star = 4},
                {CardName = "Fig",        nID = 8,  star = 4},
                {CardName = "Cherry",      nID = 9,  star = 4},
                {CardName = "Lemon",         nID = 10, star = 5},
                {CardName = "Grape",         nID = 11, star = 5},
                {CardName = "Watermelon",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "DangerousCreature",
            ThemeKey = "DangerousCreature",
            ThemeCards = {
                {CardName = "Toucan",     nID = 1,  star = 2},
                {CardName = "Golden Monkey",     nID = 2,  star = 2},
                {CardName = "Antelope",      nID = 3,  star = 3},
                {CardName = "Zebra",    nID = 4,  star = 3},
                {CardName = "Kangaroo",    nID = 5,  star = 3},
                {CardName = "Hhyena",      nID = 6,  star = 4},
                {CardName = "Wolf", nID = 7,  star = 4},
                {CardName = "Eeagle",        nID = 8,  star = 4},
                {CardName = "Puma",      nID = 9,  star = 5},
                {CardName = "Rhinoceros",         nID = 10, star = 5},
                {CardName = "Bear",         nID = 11, star = 5},
                {CardName = "Lion",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "WeLoveCandy",
            ThemeKey = "WeLoveCandy",
            ThemeCards = {
                {CardName = "Green Candy",     nID = 1,  star = 3},
                {CardName = "Square Candy",     nID = 2,  star = 3},
                {CardName = "Sandwich Candy",      nID = 3,  star = 3},
                {CardName = "Moon Candy",    nID = 4,  star = 3},
                {CardName = "Five Star Candy",    nID = 5,  star = 4},
                {CardName = "Blue Candy",      nID = 6,  star = 4},
                {CardName = "Sunflower Candy", nID = 7,  star = 4},
                {CardName = "Red Candy",        nID = 8,  star = 4},
                {CardName = "Chocolate Candy",      nID = 9,  star = 5},
                {CardName = "Cake",         nID = 10, star = 5},
                {CardName = "Bear Candy",         nID = 11, star = 5},
                {CardName = "Big Bear Candy",         nID = 12, star = 5},
            }
        },
    },

    Album2 = {
        {
            ThemeName = "WildPixies", 
            ThemeKey = "WildPixies", 
            ThemeCards = {
                {CardName = "Blue Mushroom",      nID = 1,  star = 1}, 
                {CardName = "Yellow Mushroom",   nID = 2,  star = 1},
                {CardName = "Rose",  nID = 3,  star = 1},
                {CardName = "Magic Book",    nID = 4,  star = 1},
                {CardName = "Unicorn",  nID = 5,  star = 1},
                {CardName = "Dragon",    nID = 6,  star = 1},
                {CardName = "Arwen",     nID = 7,  star = 1},
                {CardName = "Legolas",     nID = 8,  star = 2},
                {CardName = "Thranduil",   nID = 9,  star = 2},
                {CardName = "Arweil",   nID = 10, star = 2},
                {CardName = "Charlemagne",   nID = 11, star = 2},
                {CardName = "Estel",   nID = 12, star = 1}
            }
        },
        {
            ThemeName = "IrishTreasures", 
            ThemeKey = "IrishTreasures",
            ThemeCards = {
                {CardName = "Acorn",    nID = 1,  star = 1},
                {CardName = "Cookie",      nID = 2,  star = 1},
                {CardName = "Milk", nID = 3,  star = 1},
                {CardName = "Cheer",      nID = 4,  star = 1},
                {CardName = "Hammer",       nID = 5,  star = 1},
                {CardName = "Trumpet",       nID = 6,  star = 1},
                {CardName = "Beer",        nID = 7,  star = 1},
                {CardName = "Accordion",  nID = 8,  star = 2},
                {CardName = "Aoife",     nID = 9,  star = 2},
                {CardName = "Conor",    nID = 10, star = 2},
                {CardName = "Saoirse",    nID = 11, star = 2},
                {CardName = "Sean",    nID = 12, star = 2}
            }
        },
        {
            ThemeName = "VampireVsWolf",
            ThemeKey = "VampireVsWolf",
            ThemeCards = {
                {CardName = "Test Tube",       nID = 1,  star = 1},
                {CardName = "Potion",           nID = 2,  star = 1},
                {CardName = "Cross",   nID = 3,  star = 1},
                {CardName = "Candle",           nID = 4,  star = 1},
                {CardName = "Goblet",          nID = 5,  star = 1},
                {CardName = "Skull",  nID = 6,  star = 1},
                {CardName = "Machine",    nID = 7,  star = 2},
                {CardName = "Wolf",           nID = 8,  star = 2},
                {CardName = "Sincere",   nID = 9,  star = 2},
                {CardName = "Cecile",   nID = 10, star = 2},
                {CardName = "Cynthia",   nID = 11, star = 3},
                {CardName = "Shahid",   nID = 12, star = 2},
            }
        },
        {
            ThemeName = "TreasureChina",
            ThemeKey = "TreasureChina",
            ThemeCards = {
                {CardName = "Chinese Knot",       nID = 1,  star = 1},
                {CardName = "Lucky Bamboo",       nID = 2,  star = 1},
                {CardName = "Lotus",      nID = 3,  star = 1},
                {CardName = "Golden Coins",     nID = 4,  star = 1},
                {CardName = "Scroll",   nID = 5,  star = 1},
                {CardName = "Drum",       nID = 6,  star = 2},
                {CardName = "Dragon",           nID = 7,  star = 2},
                {CardName = "Fish",       nID = 8,  star = 2},
                {CardName = "Tortoise",        nID = 9,  star = 2},
                {CardName = "Toad",  nID = 10, star = 3},
                {CardName = "Panda",  nID = 11, star = 3},
                {CardName = "Pig",  nID = 12, star = 2},
            }
        },
        {
            ThemeName = "ExtraJuicy",
            ThemeKey = "ExtraJuicy",
            ThemeCards = {
                {CardName = "Apple",           nID = 1,  star = 1},
                {CardName = "Pear",               nID = 2,  star = 1},
                {CardName = "Cherry",      nID = 3,  star = 1},
                {CardName = "Plum",             nID = 4,  star = 1},
                {CardName = "Orange",           nID = 5,  star = 1},
                {CardName = "Strawberry",     nID = 6,  star = 2},
                {CardName = "Grape",  nID = 7,  star = 2},
                {CardName = "WaterMelon",          nID = 8,  star = 2},
                {CardName = "Bell",          nID = 9,  star = 2},
                {CardName = "Seven",          nID = 10, star = 3},
                {CardName = "Golden Block",          nID = 11, star = 3},
                {CardName = "Joker",          nID = 12, star = 3},
            }
        },
        {
            ThemeName = "MagicSpells",
            ThemeKey = "MagicSpells",
            ThemeCards = {
                {CardName = "Candle",        nID = 1, star = 1},
                {CardName = "Crystal",         nID = 2, star = 1},
                {CardName = "Potion",    nID = 3, star = 1},
                {CardName = "Broom",       nID = 4, star = 1},
                {CardName = "Sandglass",        nID = 5, star = 2},
                {CardName = "Skull",    nID = 6, star = 2},
                {CardName = "Pot",          nID = 7, star = 2},
                {CardName = "Magic Book",          nID = 8, star = 3},
                {CardName = "Owl",        nID = 9, star = 3},
                {CardName = "Cat",     nID = 10, star = 3},
                {CardName = "Witch",     nID = 11, star = 4},
                {CardName = "Wizard",     nID = 12, star = 4},
            }
        },
        {
            ThemeName = "HotFiesta",
            ThemeKey = "HotFiesta",
            ThemeCards = {
                {CardName = "Chilli",                   nID = 1,  star = 1},
                {CardName = "Cocktail",             nID = 2,  star = 1},
                {CardName = "Maracs",                 nID = 3,  star = 1},
                {CardName = "Hat",             nID = 4,  star = 2},
                {CardName = "Guitar",                nID = 5,  star = 2},
                {CardName = "Accordion",   nID = 6,  star = 2},
                {CardName = "Golden Coin",         nID = 7,  star = 2},
                {CardName = "Pig",                nID = 8,  star = 3},
                {CardName = "Bull",               nID = 9,  star = 3},
                {CardName = "Horse",           nID = 10, star = 4},
                {CardName = "Isabel",           nID = 11, star = 4},
                {CardName = "Santiago",           nID = 12, star = 4},
            }
        },
        {
            ThemeName = "CloverRiches",
            ThemeKey = "CloverRiches",
            ThemeCards = {
                {CardName = "Clover",        nID = 1,  star = 1},
                {CardName = "Pipe",         nID = 2,  star = 1},
                {CardName = "Beer",             nID = 3,  star = 1},
                {CardName = "Vase",               nID = 4,  star = 2},
                {CardName = "Hat",     nID = 5,  star = 2},
                {CardName = "Harp",           nID = 6,  star = 2},
                {CardName = "Horse Shoe",       nID = 7,  star = 3},
                {CardName = "Rainbow",                nID = 8,  star = 3},
                {CardName = "Golden Coin",             nID = 9,  star = 4},
                {CardName = "Golden Pot",            nID = 10, star = 4},
                {CardName = "Conor",            nID = 11, star = 4},
                {CardName = "Orla",            nID = 12, star = 4},
            }
        },
        {
            ThemeName = "ChristmasGiftRush",
            ThemeKey = "ChristmasGiftRush",
            ThemeCards = {
                {CardName = "Blue Sugar",      nID = 1,  star = 1},
                {CardName = "Green Sugar",              nID = 2,  star = 1},
                {CardName = "Hawthorn",   nID = 3,  star = 2},
                {CardName = "Bell",         nID = 4,  star = 2},
                {CardName = "Gift Box",     nID = 5,  star = 2},
                {CardName = "Stocking",        nID = 6,  star = 3},
                {CardName = "Toy Car",      nID = 7,  star = 3},
                {CardName = "Toy Bear",      nID = 8,  star = 3},
                {CardName = "Sled",         nID = 9,  star = 4},
                {CardName = "Snowman",        nID = 10, star = 4},
                {CardName = "Fox",        nID = 11, star = 5},
                {CardName = "Santa Claus",        nID = 12, star = 4},
            }
        },
        {
            ThemeName = "AliBabaGold",
            ThemeKey = "AliBabaGold",
            ThemeCards = {
                {CardName = "Shoes",         nID = 1,  star = 1},
                {CardName = "Dagger",       nID = 2,  star = 1},
                {CardName = "Magic Lamp",  nID = 3,  star = 2},
                {CardName = "Flying Carpet",         nID = 4,  star = 2},
                {CardName = "Green Gem", nID = 5,  star = 2},
                {CardName = "Pink Gem",       nID = 6,  star = 3},
                {CardName = "Necklace",      nID = 7,  star = 3},
                {CardName = "Diamond",       nID = 8,  star = 3},
                {CardName = "Crown",       nID = 9,  star = 4},
                {CardName = "Robber",    nID = 10, star = 4},
                {CardName = "Princess",    nID = 11, star = 5},
                {CardName = "Alibaba",    nID = 12, star = 5},
            }
        },
        {
            ThemeName = "HeySushi",
            ThemeKey = "HeySushi",
            ThemeCards = {
                {CardName = "Crab Warship",      nID = 1,  star = 1},
                {CardName = "Temaki",         nID = 2,  star = 1},
                {CardName = "Salmon",        nID = 3,  star = 2},
                {CardName = "Tamagoyaki",      nID = 4,  star = 2},
                {CardName = "Salmon",     nID = 5,  star = 2},
                {CardName = "Beef",          nID = 6,  star = 3},
                {CardName = "Baked Eel",      nID = 7,  star = 3},
                {CardName = "Bread",         nID = 8,  star = 4},
                {CardName = "Tuna",      nID = 9,  star = 4},
                {CardName = "Assorted",             nID = 10, star = 4},
                {CardName = "Sushi Set",             nID = 11, star = 5},
                {CardName = "Eel Over Rice",             nID = 12, star = 5},
            }
        },
        {
            ThemeName = "FairySails",
            ThemeKey = "FairySails",
            ThemeCards = {
                {CardName = "Liquor",      nID = 1,  star = 1},
                {CardName = "Swords",    nID = 2,  star = 1},
                {CardName = "Guns",      nID = 3,  star = 2},
                {CardName = "Telescope",          nID = 4,  star = 2},
                {CardName = "Pirate Hat",   nID = 5,  star = 3},
                {CardName = "Compass",        nID = 6,  star = 3},
                {CardName = "Treasure Map",         nID = 7,  star = 4},
                {CardName = "Feng",           nID = 8,  star = 4},
                {CardName = "Bohr",          nID = 9,  star = 4},
                {CardName = "BarBossa",     nID = 10, star = 5},
                {CardName = "Anne",     nID = 11, star = 5},
                {CardName = "Jack",     nID = 12, star = 5},
            }
        },
        {
            ThemeName = "BeastRiches",
            ThemeKey = "BeastRiches",
            ThemeCards = {
                {CardName = "Antelope",      nID = 1,  star = 2},
                {CardName = "Zebra",      nID = 2,  star = 2},
                {CardName = "Buffalo",    nID = 3,  star = 2},
                {CardName = "Fox",     nID = 4,  star = 3},
                {CardName = "Eagle",       nID = 5,  star = 3},
                {CardName = "Wolf",  nID = 6,  star = 3},
                {CardName = "Cheetah",    nID = 7,  star = 4},
                {CardName = "Panther",      nID = 8,  star = 4},
                {CardName = "Beer",      nID = 9,  star = 4},
                {CardName = "Tiger",      nID = 10, star = 5},
                {CardName = "Elephant",      nID = 11, star = 5},
                {CardName = "Gorilla",      nID = 12, star = 5},
            }
        },
        {
            ThemeName = "CleopatraGold",
            ThemeKey = "CleopatraGold",
            ThemeCards = {
                {CardName = "Bottle",     nID = 1,  star = 2},
                {CardName = "Eye",     nID = 2,  star = 2},
                {CardName = "Cross",      nID = 3,  star = 3},
                {CardName = "Cobra",    nID = 4,  star = 3},
                {CardName = "Ring",    nID = 5,  star = 3},
                {CardName = "Scarab",      nID = 6,  star = 4},
                {CardName = "Eagle", nID = 7,  star = 4},
                {CardName = "Bull",        nID = 8,  star = 4},
                {CardName = "Cat",      nID = 9,  star = 4},
                {CardName = "Wolf",         nID = 10, star = 5},
                {CardName = "Pharaoh",         nID = 11, star = 5},
                {CardName = "Celopatra",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "WildWest",
            ThemeKey = "WildWest",
            ThemeCards = {
                {CardName = "Dream Catcher",     nID = 1,  star = 2},
                {CardName = "Feathear",     nID = 2,  star = 2},
                {CardName = "Claw Gem",      nID = 3,  star = 3},
                {CardName = "Pipe",    nID = 4,  star = 3},
                {CardName = "Bonefire",    nID = 5,  star = 3},
                {CardName = "Drum",      nID = 6,  star = 4},
                {CardName = "Feather Crown", nID = 7,  star = 4},
                {CardName = "Golden Coin",        nID = 8,  star = 4},
                {CardName = "Tent",      nID = 9,  star = 5},
                {CardName = "Horse",         nID = 10, star = 5},
                {CardName = "Marion",         nID = 11, star = 5},
                {CardName = "Jones",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "MayaAdventure",
            ThemeKey = "MayaAdventure",
            ThemeCards = {
                {CardName = "Dagger",     nID = 1,  star = 3},
                {CardName = "Ring",     nID = 2,  star = 3},
                {CardName = "Necklace",      nID = 3,  star = 3},
                {CardName = "Goblet",    nID = 4,  star = 3},
                {CardName = "Laugh",    nID = 5,  star = 4},
                {CardName = "Death",      nID = 6,  star = 4},
                {CardName = "Beast", nID = 7,  star = 4},
                {CardName = "Man",        nID = 8,  star = 4},
                {CardName = "Golden Mask",      nID = 9,  star = 5},
                {CardName = "Temple",         nID = 10, star = 5},
                {CardName = "Queen",         nID = 11, star = 5},
                {CardName = "Chief",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "NorseMythology",
            ThemeKey = "NorseMythology",
            ThemeCards = {
                {CardName = "Harp",     nID = 1,  star = 3},
                {CardName = "Horn",     nID = 2,  star = 3},
                {CardName = "Gem",      nID = 3,  star = 3},
                {CardName = "Shield",    nID = 4,  star = 3},
                {CardName = "Ship",    nID = 5,  star = 4},
                {CardName = "Helmet",      nID = 6,  star = 4},
                {CardName = "Treature Chest", nID = 7,  star = 4},
                {CardName = "Hladgunnr",        nID = 8,  star = 4},
                {CardName = "Alvitr",      nID = 9,  star = 5},
                {CardName = "Loki",         nID = 10, star = 5},
                {CardName = "Sol",         nID = 11, star = 5},
                {CardName = "Odin",         nID = 12, star = 5},
            }
        },
        {
            ThemeName = "SweetBonanza",
            ThemeKey = "SweetBonanza",
            ThemeCards = {
                {CardName = "Cloud",     nID = 1,  star = 3},
                {CardName = "Solid",     nID = 2,  star = 3},
                {CardName = "Chocolate Story",      nID = 3,  star = 3},
                {CardName = "Cherry Flavor",    nID = 4,  star = 3},
                {CardName = "Order",    nID = 5,  star = 4},
                {CardName = "Fish",      nID = 6,  star = 4},
                {CardName = "Castle Top", nID = 7,  star = 4},
                {CardName = "Dream",        nID = 8,  star = 4},
                {CardName = "Love",      nID = 9,  star = 5},
                {CardName = "Nuddle",         nID = 10, star = 5},
                {CardName = "Forest",         nID = 11, star = 5},
                {CardName = "Surf",         nID = 12, star = 5},
            }
        },
    },
}

