ChutesRocketsItemType = { 
    enumItem_Normal = 0,
    enumItem_Rocket = 1,
    enumItem_Slide = 2,
    enumItem_Gift = 3
}

ChutesRocketsLevelConfig = {
    ChutesRocketsLevel1 = {
        N_MAX_GRID_COUNT = 60,
        N_NORNAL_REWARD = 1000000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 3},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 10},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 14},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 20},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 25},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 32},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 42},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 47},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 52},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 57},

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 5, nTarget = 25},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 8, nTarget = 31},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 21, nTarget = 37},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 27, nTarget = 47},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 39, nTarget = 57},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 48, nTarget = 52},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 28, nTarget = 6},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 43, nTarget = 17},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 55, nTarget = 36},
        }
    },
    ChutesRocketsLevel2 = {
        N_MAX_GRID_COUNT = 80,
        N_NORNAL_REWARD = 1200000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 5},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 13},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 18},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 26},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 30},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 35},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 39},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 41},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 49},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 57},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 66},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 67},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 72},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 76},

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 4, nTarget = 20},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 7, nTarget = 32},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 12, nTarget = 30},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 24, nTarget = 74},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 27, nTarget = 35},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 38, nTarget = 57},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 50, nTarget = 67},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 59, nTarget = 77},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 19, nTarget = 8},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 34, nTarget = 17},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 55, nTarget = 43},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 58, nTarget = 21},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 73, nTarget = 49},
        }
    },
    ChutesRocketsLevel3 = {
        N_MAX_GRID_COUNT = 100,
        N_NORNAL_REWARD = 1400000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 5},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 11},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 13},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 19},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 24},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 33},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 43},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 46},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 52},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 61},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 73},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 76},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 83},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 92},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 97},

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 3, nTarget = 40},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 7, nTarget = 16},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 10, nTarget = 33},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 23, nTarget = 43},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 27, nTarget = 95},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 35, nTarget = 54},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 50, nTarget = 72},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 56, nTarget = 63},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 60, nTarget = 79},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 25, nTarget = 5},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 28, nTarget = 9},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 37, nTarget = 19},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 53, nTarget = 26},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 64, nTarget = 59},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 85, nTarget = 46},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 94, nTarget = 73},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 98, nTarget = 78},
        }
    },
    ChutesRocketsLevel4 = {
        N_MAX_GRID_COUNT = 120,
        N_NORNAL_REWARD = 1600000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 8},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 17},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 23},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 30},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 34},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 43},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 56},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 67},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 73},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 79},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 85},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 93},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 101},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 105},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 112},
            

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 4, nTarget = 25},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 10, nTarget = 33},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 18, nTarget = 39},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 35, nTarget = 67},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 50, nTarget = 79},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 78, nTarget = 99},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 89, nTarget = 107},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 103, nTarget = 118},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 27, nTarget = 9},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 36, nTarget = 24},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 40, nTarget = 19},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 48, nTarget = 26},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 66, nTarget = 41},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 100, nTarget = 60},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 104, nTarget = 76},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 108, nTarget = 77},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 113, nTarget = 91},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 119, nTarget = 98},
        }
    },
    ChutesRocketsLevel5 = {
        N_MAX_GRID_COUNT = 140,
        N_NORNAL_REWARD = 1800000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 5},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 14},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 22},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 32},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 36},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 43},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 53},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 55},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 61},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 78},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 88},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 93},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 95},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 104},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 111},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 122},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 128},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 136},

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 7, nTarget = 53},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 23, nTarget = 60},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 26, nTarget = 84},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 29, nTarget = 50},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 37, nTarget = 95},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 46, nTarget = 74},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 71, nTarget = 136},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 72, nTarget = 128},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 81, nTarget = 116},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 100, nTarget = 123},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 34, nTarget = 28},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 42, nTarget = 4},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 47, nTarget = 25},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 89, nTarget = 51},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 117, nTarget = 61},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 124, nTarget = 55},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 127, nTarget = 75},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 129, nTarget = 93},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 135, nTarget = 115},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 139, nTarget = 120},
        }
    },
    ChutesRocketsLevel6 = {
        N_MAX_GRID_COUNT = 180,
        N_NORNAL_REWARD = 2000000,
        TABLE_SPECIAL_GRID = {
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 9},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 16},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 38},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 47},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 52},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 56},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 61},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 73},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 86},

            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 90},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 94},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 104},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 123},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 132},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 142},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 147},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 152},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 157},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 165},
            {enumType = ChutesRocketsItemType.enumItem_Gift, nID = 178},

            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 7, nTarget = 53},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 23, nTarget = 60},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 26, nTarget = 84},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 29, nTarget = 50},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 37, nTarget = 94},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 46, nTarget = 74},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 71, nTarget = 136},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 72, nTarget = 128},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 81, nTarget = 116},
            {enumType = ChutesRocketsItemType.enumItem_Rocket, nID = 100, nTarget = 123},

            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 45, nTarget = 4},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 51, nTarget = 12},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 54, nTarget = 28},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 62, nTarget = 22},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 84, nTarget = 61},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 88, nTarget = 56},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 95, nTarget = 86},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 120, nTarget = 97},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 129, nTarget = 110},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 138, nTarget = 119},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 144, nTarget = 116},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 151, nTarget = 128},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 154, nTarget = 126},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 161, nTarget = 112},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 173, nTarget = 149},
            {enumType = ChutesRocketsItemType.enumItem_Slide, nID = 177, nTarget = 165},
        }
    }
}